version: '3'

services:
  backend:
    build: ./backend
    container_name: hello-world-backend
    restart: always
    environment:
      - PORT=8080
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: hello-world-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      # Use a named volume to avoid path issues
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge