# Use the official Golang image
FROM golang:1.23-alpine as build

# Set the Current Working Directory inside the container
WORKDIR /app

# Download Go modules
COPY go.mod go.sum ./
RUN go mod download

# Copy the source code into the container
RUN go mod tidy

# Copy the source code into the container
COPY backend-goFiber/ .

# Build
RUN CGO_ENABLED=0 GOOS=linux go build -o /docker-gs-ping

FROM alpine:latest

WORKDIR /root/

COPY --from=build /app/main .

EXPOSE 3000

# Run
CMD ["./app"]